### ISSUE TITLE
Blener Importing json file problem

### ISSUE THREAD

**Issue by mindsetmastery** [adroitwhiz/after-effects-to-blender-export#18] opened 2024-02-21 09:43 UTC
I'm having trouble locating the exported JSON file from After Effects when attempting to import it into Blender.

**Comment by adroitwhiz** [comment] 2024-02-22 10:39
See https://github.com/adroitwhiz/after-effects-to-blender-export/issues/13?

**Comment by adroitwhiz** [comment] 2024-04-06 11:28
Going to assume this is a duplicate of #13, which I've fixed. Feel free to reopen if you can't get this working.

**Closed by adroitwhiz** 2024-04-06 11:28 UTC
